# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommender.proto',
  package='recommender',
  syntax='proto3',
  serialized_options=b'\nEcom.intel.analytics.bigdl.friesian.serving.grpc.generated.recommenderB\020RecommenderProto\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11recommender.proto\x12\x0brecommender\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x07IDProbs\x12\n\n\x02ID\x18\x01 \x03(\x05\x12\x0c\n\x04prob\x18\x02 \x03(\x02\"J\n\x10RecommendRequest\x12\x14\n\x0crecommendNum\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidateNum\x18\x02 \x01(\x05\x12\n\n\x02ID\x18\x03 \x03(\x05\"<\n\x10RecommendIDProbs\x12(\n\nIDProbList\x18\x01 \x03(\x0b\x32\x14.recommender.IDProbs\"\x1c\n\rServerMessage\x12\x0b\n\x03str\x18\x01 \x01(\t2\xb0\x02\n\x0bRecommender\x12Q\n\x0fgetRecommendIDs\x12\x1d.recommender.RecommendRequest\x1a\x1d.recommender.RecommendIDProbs\"\x00\x12\x42\n\ngetMetrics\x12\x16.google.protobuf.Empty\x1a\x1a.recommender.ServerMessage\"\x00\x12@\n\x0cresetMetrics\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12H\n\x10getClientMetrics\x12\x16.google.protobuf.Empty\x1a\x1a.recommender.ServerMessage\"\x00\x42_\nEcom.intel.analytics.bigdl.friesian.serving.grpc.generated.recommenderB\x10RecommenderProto\xa2\x02\x03RTGb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_IDPROBS = _descriptor.Descriptor(
  name='IDProbs',
  full_name='recommender.IDProbs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='recommender.IDProbs.ID', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prob', full_name='recommender.IDProbs.prob', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=98,
)


_RECOMMENDREQUEST = _descriptor.Descriptor(
  name='RecommendRequest',
  full_name='recommender.RecommendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendNum', full_name='recommender.RecommendRequest.recommendNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candidateNum', full_name='recommender.RecommendRequest.candidateNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ID', full_name='recommender.RecommendRequest.ID', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=174,
)


_RECOMMENDIDPROBS = _descriptor.Descriptor(
  name='RecommendIDProbs',
  full_name='recommender.RecommendIDProbs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='IDProbList', full_name='recommender.RecommendIDProbs.IDProbList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=236,
)


_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='recommender.ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='recommender.ServerMessage.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=266,
)

_RECOMMENDIDPROBS.fields_by_name['IDProbList'].message_type = _IDPROBS
DESCRIPTOR.message_types_by_name['IDProbs'] = _IDPROBS
DESCRIPTOR.message_types_by_name['RecommendRequest'] = _RECOMMENDREQUEST
DESCRIPTOR.message_types_by_name['RecommendIDProbs'] = _RECOMMENDIDPROBS
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDProbs = _reflection.GeneratedProtocolMessageType('IDProbs', (_message.Message,), {
  'DESCRIPTOR' : _IDPROBS,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:recommender.IDProbs)
  })
_sym_db.RegisterMessage(IDProbs)

RecommendRequest = _reflection.GeneratedProtocolMessageType('RecommendRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDREQUEST,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:recommender.RecommendRequest)
  })
_sym_db.RegisterMessage(RecommendRequest)

RecommendIDProbs = _reflection.GeneratedProtocolMessageType('RecommendIDProbs', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDIDPROBS,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:recommender.RecommendIDProbs)
  })
_sym_db.RegisterMessage(RecommendIDProbs)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:recommender.ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)


DESCRIPTOR._options = None

_RECOMMENDER = _descriptor.ServiceDescriptor(
  name='Recommender',
  full_name='recommender.Recommender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=269,
  serialized_end=573,
  methods=[
  _descriptor.MethodDescriptor(
    name='getRecommendIDs',
    full_name='recommender.Recommender.getRecommendIDs',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDREQUEST,
    output_type=_RECOMMENDIDPROBS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getMetrics',
    full_name='recommender.Recommender.getMetrics',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='resetMetrics',
    full_name='recommender.Recommender.resetMetrics',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getClientMetrics',
    full_name='recommender.Recommender.getClientMetrics',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SERVERMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDER)

DESCRIPTOR.services_by_name['Recommender'] = _RECOMMENDER

# @@protoc_insertion_point(module_scope)
